{% set name = "e1" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/e1-{{ version }}.tar.gz
  sha256: f49ed551496db8f8f05ca994089dea6f2f3d281cdd2498d63349a804fd7f9a3e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - e1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LANL-seismoacoustics/e1
  summary: Python support for the e1 compression format.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jkmacc-LANL
    - jcox10
